task: extrap     
train_data_path: '../../data/ODEs/pendulum/nonlinear.pkl'
batch_size: 32
num_workers: 1
extrap_val_split: 0.7
extrap_test_split: 0.85     

embed_dim: 128
latent_dim: 1
freq: 4.0
damp: 0.5
length_scale: 1.0
trainable_params: true
trainable_ls: false
amp: false
scale: true

ckpt_root: "/home/kendra/Code/Learning-Dynamics-Latent-Force/scripts/pendulum_training/model_checkpoints"
max_epochs: 4000
val_check: 1000
log_every_n_steps: 250
make_gifs: true

seed: 0
