task: recon                
train_data_path: '../../data/ODEs/pendulum/nonlinear.pkl'
batch_size: 32
num_workers: 1
val_fraction: 0.10         
test_fraction: 0.10        

embed_dim: 128
latent_dim: 1

ckpt_root: "/home/kendra/Code/Learning-Dynamics-Latent-Force/scripts/pendulum_training/model_checkpoints"
max_epochs: 4000
val_check: 250
log_every_n_steps: 250
make_gifs: true

seed: 0
